//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoveToLerningEntities : DbContext
    {
        public LoveToLerningEntities()
            : base("name=LoveToLerningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiplomasToLimitToTeacher> DiplomasToLimitToTeacher { get; set; }
        public virtual DbSet<Lessons> Lessons { get; set; }
        public virtual DbSet<Limit> Limit { get; set; }
        public virtual DbSet<LimitToTeacher> LimitToTeacher { get; set; }
        public virtual DbSet<Recommendation> Recommendation { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Sector> Sector { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Times> Times { get; set; }
        public virtual DbSet<TimeToUser> TimeToUser { get; set; }
        public virtual DbSet<TryToLimitToTeacher> TryToLimitToTeacher { get; set; }
        public virtual DbSet<Useres> Useres { get; set; }
        public virtual DbSet<Waiting> Waiting { get; set; }
    }
}
