//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recommendation
    {
        public int CodeRecommendation { get; set; }
        public Nullable<int> CodeLimitToTeacher { get; set; }
        public string RecommendationText { get; set; }
        public Nullable<bool> Reply { get; set; }
        public Nullable<bool> NotTime { get; set; }
        public Nullable<int> CodeUser { get; set; }
    
        public virtual LimitToTeacher LimitToTeacher { get; set; }
    }
}
