//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeToUser
    {
        public int CodeTimeToUser { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdTime { get; set; }
    
        public virtual Times Times { get; set; }
        public virtual Useres Useres { get; set; }
    }
}
