//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TryToLimitToTeacher
    {
        public int CodeTryToLimitToTeacher { get; set; }
        public int CodeLimitToTeacher { get; set; }
        public string NamePlaceTeach { get; set; }
        public string MailRecommend { get; set; }
        public string PhoneRecommend { get; set; }
    
        public virtual LimitToTeacher LimitToTeacher { get; set; }
    }
}
