//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waiting
    {
        public int WaitingID { get; set; }
        public Nullable<int> CodeUser { get; set; }
        public Nullable<int> CodeLimit { get; set; }
        public Nullable<int> CodeTime { get; set; }
        public Nullable<int> CodeMin { get; set; }
        public Nullable<int> CodeSector { get; set; }
    
        public virtual Limit Limit { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Times Times { get; set; }
        public virtual Useres Useres { get; set; }
    }
}
